name: countr-kiosk
version: '0.0.1'
summary: Countr Desktop Kiosk Mode
description: |
  Countr Desktop Kiosk Mode
base: core18
confinement: devmode
grade: devel
compression: lzo

apps:
  countr-desktop:
    daemon: simple
    extensions: [gnome-3-34]
    restart-condition: always
    command: snap/command-chain/desktop-launch xwayland-kiosk-launch $SNAP/countr-kiosk --no-sandbox
    plugs:
      - browser-support
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"

parts:
  countr-kiosk:
    plugin: nil
    source: .
    override-build: |
      npm install electron-builder
      ./node_modules/.bin/electron-builder --dir --armv7l --linux snap
    stage-packages:
      - libnspr4
      - libnss3
    build-snaps:
      - node/14/stable

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [build-essential]
    stage-packages: [xwayland, i3, libegl1-mesa, libgl1-mesa-glx]
